name: Lingmo OS Autobuild

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget build-essential autoconf automake \
            extra-cmake-modules libkf5configwidgets-dev libkf5i18n-dev \
            libkf5config-dev libkf5iconthemes-dev libkf5guiaddons-dev \
            rsync file lingmo-pkgbuild

      - name: Initialize Project
        run: |
          cd $GITHUB_WORKSPACE
          make config-pkgs

      - name: Build Packages
        run: |
          cd $GITHUB_WORKSPACE
          make build-pkgs
          make third-party

      - name: Build ISO
        run: |
          cd $GITHUB_WORKSPACE
          # فرض می‌کنیم make target برای ISO هست
          make image-iso || echo "ISO generation failed"

      - name: Create release directory
        run: |
          mkdir -p release
          mv *.iso release/ || true

      - name: Create release tarball
        run: |
          tar -cJf release.tar.xz -C release .

      - name: Set Release Tag
        id: set_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}-build-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.TAG_NAME }}" \
            --title "Release ${{ env.TAG_NAME }}" \
            --notes "Automated build for Lingmo OS" \
            release.tar.xz

          for file in release/*; do
            if [ -f "$file" ]; then
              echo "Uploading $(basename "$file")"
              gh release upload "${{ env.TAG_NAME }}" "$file"
            fi
          done
